### ISSUE TITLE
proposal: make lovelace-gen a plugin of homeassistant-cli

### ISSUE THREAD

**Issue by maxandersen** [thomasloven/homeassistant-lovelace-gen#10]
Hi!

I would like to propose to make lovelace-gen a plugin of home-assistant-cli. WIP PR for that is at https://github.com/home-assistant/home-assistant-cli/pull/104

Would like to hear what your thought is on that ?

The above PR is a literal verbatim copy of lovelace-gen with all its features (and bugs :) intact - would like to clean it up a bit so the various lint/typing hints passes; but didn't want to do that before hearing you thoughts on it.

btw. you simply run it by doing `hass-cli lovelace-gen` instead of `python3 lovelace-gen.py` - same arguments and option supported.

Background: 
I've been working on https://github.com/home-assistant/home-assistant-cli's and one of its features is its `template` plugin that does generic local and server side templates for homeassistant. Kind of a superset of lovelace-gen.

I was starting to mimick lovelace-gen features of `!include`, `!secret` etc. as they are generally useful but then thought - why not have lovelace-gen as a plugin directly to start and then align from there.

btw. how come you removed the feature of grabbing HA current state for use in templates ? something I was planning to add to the template support in home-assistant-cli as it can be quite useful.

In any case - let me know what you think and we can figure out best way to get it aligned.

**Comment by maxandersen** [comment]
note - added an additional commit to fix #11 so it doesn't drop quotes.

**Comment by thomasloven** [comment]
I'm not really sure what to think about this...

`!include` (with more variants) and `!secret` are already supported natively in ui-lovelace.yaml, and the templating is of limited use to most people. Since the pending removal of `!Include` support was the reason lovelace-gen even came to be, it's actually pretty much deprecated now anyway...
The remaining reason to use lovelace-gen is the templating, which - while convenient for advanced users - have limited use for most people and goes against the current path of lovelace development.
In fact, I believe using a generator such as lovelace-gen or hass-cli detracts from the user experience by requiring an extra step while developing the layout.

I keep lovelace-gen around and update it hoping to stumble on a "killer feature" for it, something to make it relevant again that couldn't be done natively (which I'm hoping templates might be eventually - to an extent).

However - in the end it all comes down to personal preference about your workflow - so if you can get the hass-cli maintainer on board with the idea, I certainly won't try to stop you.

The reason I removed the state templates is threefold
- I found it hard to explain - never a good sign
- It required api_password - may consider putting it back with LTAT-support
- I didn't think anyone was using it - even me

Perhaps putting it in hass-cli could solve the first two points, though...

**Comment by maxandersen** [comment]
hmm - wasn't aware of !include and !secret being natively in ui-lovelace.yaml - got a pointer for that since only thing I've seen was hesitance to put it back in again ?

About the templating that is actually why I use it since I just got too frustrated having to update and see the same block of yaml referenced 10ish times on my floorplan.

About convincing maintainer of home-assistant-cli then thats not hard as thats currently me :)
And part of what I've done is to add a basic `hass-cli template` initially to get better flow working on generating configuration.yaml since I find myself having so many repeated elements that I just don't want to maintain by hand.
 
Here is what I'll do - once I learn more about native support for lovelace include and secret support I'll see whats left and if include/secret and !file to not forget is relevant I'll probably add that kind of support to `hass-cli template` support as it at least makes my updates to the configuration much simpler.

about the loading of state templates, I actually was planning on adding a "experiemental" flag or similar to not just get the state map but also the device registry so could iterate the setup and generate nice docs/overview.

**Comment by maxandersen** [comment]
coming back to this and yes, lovelace have native support for includes now, last thing is the !file feature but that is trivial to do if using normal templating feature. 

closing this as not relevant anymore. thanks.
