### ISSUE TITLE
Syntax error on author's name

### ISSUE THREAD

**Issue by iantrich** [thomasloven/homeassistant-lovelace-gen#3]
SyntaxError: Non-ASCII character '\xc3' in file /config/lovelace-gen.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by thomasloven** [comment]
You are trying to run it using python2.
This is bad because

- It should be run in the same environment as hass (which doesn't support python2)
- It clearly says python3 on the first line of the script
- Running the script as instructed (through the shell) will automatically run it using python3
- It's 2018

Try python3 instead

**Comment by iantrich** [comment]
Sorry about that. Was running within the Cloud9 IDE add-on which has an integrated terminal and didn't even think to check the Python version. Thanks.

**Comment by thomasloven** [comment]
It's a shame they don't have python3 as default... but that's a borderline political question...
